(function($){let ajaxFlag=null;Highcharts.setOptions({accessibility:{enabled:false},chart:{panning:{enabled:false}},title:{text:''},stockTools:{gui:{enabled:false}},scrollbar:{enabled:false},credits:{enabled:false},navigator:{enabled:false},rangeSelector:{enabled:false},tooltip:{borderWidth:0,borderRadius:4,formatter(){let s='<b>'+Highcharts.dateFormat('%a %b %e %Y, %H:%I:%S',this.x)+'</b><br/>';this.points.forEach(point=>{if(point.colorIndex=='primary-volume'||point.series.name=='Volume'){s+='<br/><b>Vol: </b>$'+numberFormat(point.y,0);}else{if(point.series.name=='Price'){var price=point.y
if(point.y>1){price=numberFormat(point.y,2);}else{price=numberFormat(point.y,6);}
s+='<br/><b>'+point.series.name+': </b>$'+price;}else if(point.series.name=='Users'||point.series.name=='Transactions'){s+='<br/><b>'+point.series.name+': </b>'+numberFormat(point.y,0);}else{s+='<br/><b>'+point.series.name+': </b>'+point.y;}}});return s;}}});function numberFormatShort($n){var $n_format=0,$suffix='';$n=parseFloat($n);if($n>0&&$n<1000){$n_format=($n).toFixed(2);$suffix='';}else if($n>=1000&&$n<1000000){$n_format=($n/1000).toFixed(2);$suffix='K';}else if($n>=1000000&&$n<1000000000){$n_format=($n/1000000).toFixed(2);$suffix='M';}else if($n>=1000000000&&$n<1000000000000){$n_format=($n/1000000000).toFixed(2);$suffix='B';}else if($n>=1000000000000){$n_format=($n/1000000000000).toFixed(2);$suffix='T';}
return $n_format+$suffix;}
function escapeHtml(str){return String(str).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));}
function numberFormat(number,decimals,dec_point,thousands_sep){number=(number+'').replace(/[^0-9+\-Ee.]/g,'');var n=!isFinite(+number)?0:+number,prec=!isFinite(+decimals)?0:Math.abs(decimals),sep=(typeof thousands_sep==='undefined')?',':thousands_sep,dec=(typeof dec_point==='undefined')?'.':dec_point,s='',toFixedFix=function(n,prec){var k=Math.pow(10,prec);return''+Math.round(n*k)/k;};s=(prec?toFixedFix(n,prec):''+Math.round(n)).split('.');if(s[0].length>3){s[0]=s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g,sep);}
if((s[1]||'').length<prec){s[1]=s[1]||'';s[1]+=new Array(prec-s[1].length+1).join('0');}
return s.join(dec);}
function removeURLParameter(url,parameter){var urlparts=url.split('?');if(urlparts.length>=2){var prefix=encodeURIComponent(parameter)+'=';var pars=urlparts[1].split(/[&;]/g);for(var i=pars.length;i-->0;){if(pars[i].lastIndexOf(prefix,0)!==-1){pars.splice(i,1);}}
return urlparts[0]+(pars.length>0?'?'+pars.join('&'):'');}
return url;}
$(document).ready(function(){if($('.game-subnav').length){$('#page-content').scrollspy({target:'.game-subnav'});$('.game-subnav .nav__btn').each(function(){const target=$(this).attr('href');if(target&&target.startsWith('#')&&!$(target).length){$(this).closest('li').hide();}});}
if($('.game-gallery').length){new Swiper('.game-gallery',{slidesPerView:1,spaceBetween:20,navigation:{nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev',},breakpoints:{576:{slidesPerView:2},992:{slidesPerView:3},1200:{slidesPerView:4}}});$('.game-gallery').magnificPopup({delegate:'a',type:'image',gallery:{enabled:true,navigateByImgClick:true,preload:[0,1]}});}
$('.game-news .swiper').each(function(){const $swiper=$(this);new Swiper($swiper[0],{slidesPerView:1,spaceBetween:16,navigation:{nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev',},breakpoints:{576:{slidesPerView:2},992:{slidesPerView:3},1200:{slidesPerView:4}}});});$('.game-related .swiper').each(function(){const $swiper=$(this);new Swiper($swiper[0],{slidesPerView:2,spaceBetween:20,pagination:{el:'.swiper-pagination',clickable:true},breakpoints:{576:{slidesPerView:3},768:{slidesPerView:4},992:{slidesPerView:5},1200:{slidesPerView:6}}});});function changeWatchlistIcon(){var flag=$('#sg-header div.add-watchlist ul.dropdown-menu li a.added');if(flag.length){$('#sg-header .sg-header__name span.watchlist-icon').addClass('added');}else{$('#sg-header .sg-header__name span.watchlist-icon').removeClass('added');}}
changeWatchlistIcon();$('#sg-header div.add-watchlist ul.dropdown-menu').on('click','a',function(e){var $this=$(this),href=$this.attr('href');e.stopPropagation();if(href){var watchlistID=href.replace('#',''),gameTitle=$('#sg-header h1').html(),jsonURL='',jsonData={};if(ajaxFlag){ajaxFlag.abort();}
if($this.hasClass('added')){jsonURL=cpJson.cp_url+'/watchlist/remove-game';jsonData={watchlist_id:watchlistID,remove_id:cpLocalize.post_id};}else{jsonURL=cpJson.cp_url+'/watchlist/add-game';jsonData={watchlist_id:watchlistID,add_id:cpLocalize.post_id};}
if(jsonURL&&jsonData){ajaxFlag=$.ajax({url:jsonURL,method:'POST',dataType:'json',data:jsonData,beforeSend:function(xhr){xhr.setRequestHeader('X-WP-Nonce',cpJson.nonce);$this.addClass('loading');}}).done(function(response){$this.removeClass('loading');if(response&&response.success&&response.data&&response.data.title){var message='';if($this.hasClass('added')){message='<strong>'+gameTitle+'</strong>'+' removed from '+'<strong>'+response.data.title+'</strong>',$this.removeClass('added');}else{message='<strong>'+gameTitle+'</strong>'+' added to '+'<strong>'+response.data.title+'</strong>';$this.addClass('added');}
if(message){if(response.data.link){$('#notification .btn').attr('href',response.data.link).html('View your watchlist');}
$('#notification .message').html(message);$('#notification').toast('show');}
changeWatchlistIcon();}});}}});$('#new-watchlist').on('shown.bs.modal',function(e){$('#new-watchlist form input[name="name"]').focus();});$('#new-watchlist form').on('submit',function(e){var form=$(this),nameField=form.find('input[name="name"]'),button=form.find('button[type="submit"]'),gameTitle=$('#sg-header h1').html();e.preventDefault();if(!nameField.val()){nameField.focus();return;}
if(ajaxFlag){ajaxFlag.abort();}
ajaxFlag=$.ajax({url:cpJson.cp_url+'/watchlist/update',method:'POST',dataType:'json',data:{form_data:form.serialize(),add_id:cpLocalize.post_id},beforeSend:function(xhr){xhr.setRequestHeader('X-WP-Nonce',cpJson.nonce);button.attr('disabled','disabled');}}).done(function(response){button.removeAttr('disabled');if(response&&response.success&&response.data&&response.data.title&&response.data.id){var message='<strong>'+gameTitle+'</strong>'+' added to '+'<strong>'+response.data.title+'</strong>';nameField.val('');$('#new-watchlist').modal('toggle');$('#sg-header .sg-header__name .dropdown-menu').prepend('<li><a href="#'+response.data.id+'" class="added">'+response.data.title+'</a></li>');if(response.data.link){$('#notification .btn').attr('href',response.data.link).html('View your watchlist');}
$('#notification .message').html(message);$('#notification').toast('show');}});});});$(window).on('load',function(){if($('#onchain-chart__render').length){var options={legend:{enabled:true,align:'left',verticalAlign:'top',borderWidth:0},yAxis:[{labels:{align:'left',x:0,y:-2},opposite:false,height:'33.333%',resize:{enabled:true}},{labels:{align:'left',x:0,y:-2},opposite:false,top:'33.333%',height:'33.333%',resize:{enabled:true}},{labels:{align:'left',x:0,y:-2},opposite:false,top:'66.666%',height:'33.333%',resize:{enabled:true}}],series:[{type:'line',id:'onchain-users',name:'Users',dataGrouping:{enabled:false},yAxis:0,colorIndex:'primary',color:'#d71c5d',lineWidth:1},{type:'line',id:'onchain-transactions',name:'Transactions',dataGrouping:{enabled:false},yAxis:1,colorIndex:'primary',color:'#FF9017',lineWidth:1},{type:'line',id:'onchain-volume',name:'Volume',dataGrouping:{enabled:false},yAxis:2,colorIndex:'primary-volume',color:'#16c784'}]}
function updateChart(days=30){let jsonUrl=cpJson.cp_url+'/on-chain/'+cpLocalize.post_id+'/'+days;$.ajax({url:jsonUrl,method:'GET',dataType:'json',beforeSend:function(xhr){xhr.setRequestHeader('X-WP-Nonce',cpJson.nonce);}}).success(function(response){if(response&&response.users&&response.transactions&&response.volume){options.series[0].data=response.users;options.series[1].data=response.transactions;options.series[2].data=response.volume;Highcharts.stockChart('onchain-chart__render',options);}else{$('#onchain-chart').hide();}});}
updateChart();$('#onchain-chart .chart-toolbar button').on('click',function(e){let days=$(this).attr('data-days');if(days){updateChart(days);}
$('#onchain-chart .chart-toolbar button').removeClass('active');$(this).addClass('active');e.preventDefault();});}});$(window).on('load',function(){let chart;const options={yAxis:[{labels:{formatter(){return'$'+this.value;},align:'left',x:0,y:-2},opposite:false,height:'80%',resize:{enabled:true}},{labels:{enabled:false,align:'left',x:0,y:-2},opposite:false,top:'80%',height:'20%',offset:0}],series:[{type:'line',id:'game-price',name:'Price',dataGrouping:{enabled:false},colorIndex:'primary',color:'#FF9017',lineWidth:1},{type:'column',id:'game-volume',name:'Volume',dataGrouping:{enabled:false},yAxis:1,colorIndex:'primary-volume',color:'#16c784'}]}
function updateChart(days='1'){const apiUrl=`https://api.coingecko.com/api/v3/coins/${cpLocalize.cgk_api_id}/market_chart?vs_currency=usd&days=${days}`;fetch(apiUrl).then(response=>response.json()).then(function(data){if(data?.prices&&data?.total_volumes){if(!chart){options.series[0].data=data.prices;options.series[1].data=data.total_volumes;chart=Highcharts.stockChart('price-chart__render',options);}else{chart.series[0].setData(data.prices,false);chart.series[1].setData(data.total_volumes,false);chart.redraw();}}}).catch(err=>console.error('Error fetching data:',err));}
if($('#price-chart__render').length&&cpLocalize.cgk_api_id){updateChart();$('#price-chart').on('click','.chart-toolbar__btn',function(e){e.preventDefault();const days=$(this).attr('data-days');if(days){updateChart(days);}
$('#price-chart .chart-toolbar__btn').removeClass('active');$(this).addClass('active');});}});$(window).on('load',function(){if(!cpLocalize.cgk_api_id){$('#where-buy').hide();return;}
const apiUrl=`https://api.coingecko.com/api/v3/coins/${cpLocalize.cgk_api_id}/tickers?include_exchange_logo=true&order=volume_desc`;fetch(apiUrl).then(res=>res.json()).then(data=>{if(!data.tickers||!data.tickers.length){$('#where-buy').hide();return;}
let rows='';data.tickers.slice(0,10).forEach((ticker,i)=>{const marketName=escapeHtml(ticker.market?.name||'');const logo=ticker.market?.logo?`<img src="${escapeHtml(ticker.market.logo)}" class="exchange__logo" alt="${marketName}" />`:'';const tradeUrl=ticker.trade_url?removeURLParameter(ticker.trade_url,'ref'):'';const base=escapeHtml(ticker.base||'');const target=escapeHtml(ticker.target||'');const price=parseFloat(ticker.converted_last?.usd||0);const spread=ticker.bid_ask_spread_percentage?.toFixed(3)||'';const volume=ticker.converted_volume?.usd?`$${numberFormat(parseFloat(ticker.converted_volume.usd))}`:'';const trust=escapeHtml(ticker.trust_score||'');rows+=`
						<tr>
							<td class="text-center">${i + 1}</td>
							<td class="text-start">
								<div class="exchange">${logo}<strong>${marketName}</strong></div>
							</td>
							<td class="text-start">
								${tradeUrl ? `<a href="${escapeHtml(tradeUrl)}"target="_blank"rel="noopener noreferrer">` : ''}
									<strong>${base}/${target}</strong>
								${tradeUrl ? `</a>` : ''}
							</td>
							<td>${price ? `$${price>=1?price.toFixed(2):price.toFixed(5)}` : ''}</td>
							<td>${spread ? `${spread}%` : ''}</td>
							<td>${volume}</td>
							<td>Recently</td>
							<td class="text-center">${trust ? `<span class="trust-score d-block mx-auto overflow-hidden ${trust}">${trust}</span>` : ''}</td>
						</tr>
					`;});$('#where-buy table tbody').html(rows);}).catch(err=>{console.error('CoinGecko API error:',err);$('#where-buy').hide();});});})(jQuery);